# ClimateWins Weather Prediction : Keras Layered Model (CNN)

## This Script contains: 
### 1. Import Libraries and Data.
### 2. Data Wrangle
### 3. Data Reshape
### 4. Data Splitting
### 5. Keras Model
### 6. Compile and Running Model
### 7. Confusion Matrix
### 8. Keras Model Retrials

In [5]:
# Import libraries and Data
import pandas as pd
import numpy as np
import seaborn as sns
import os
import operator
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from numpy import unique
from numpy import reshape
from keras.models import Sequential
from keras.layers import Conv1D, Conv2D, Dense, BatchNormalization, Flatten, MaxPooling1D, Dropout
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import warnings
warnings.filterwarnings("ignore")

In [6]:
# Create a path where data is stored
path = r'/Users/amritkaur/Desktop/CAREERFOUNDRY/Machine Learning/Achievement 2/Data Sets'

In [7]:
# Import the datasets
unscaled= pd.read_csv(os.path.join(path, 'Dataset-weather-prediction-dataset-processed raw.csv'))
prediction = pd.read_csv(os.path.join(path, 'Dataset-Answers-Weather_Prediction_Pleasant_Weather.csv'))

unscaled.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,2.1,0.85,1.018,0.32,0.09,0,0.7,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,19600102,1,6,2.1,0.84,1.018,0.36,1.05,0,1.1,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,19600103,1,8,2.1,0.90,1.018,0.18,0.30,0,0.0,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,19600104,1,3,2.1,0.92,1.018,0.58,0.00,0,4.1,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,19600105,1,6,2.1,0.95,1.018,0.65,0.14,0,5.4,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

In [8]:
unscaled.shape

(22950, 170)

## 2. Data Wrangle

In [10]:
# Remove weather stations not included in "pleasant weather" answers
unscaled = unscaled.drop(['GDANSK_cloud_cover', 'GDANSK_humidity', 'GDANSK_precipitation', 'GDANSK_snow_depth', 'GDANSK_temp_mean', 'GDANSK_temp_min', 'GDANSK_temp_max',
                        'ROMA_cloud_cover', 'ROMA_wind_speed', 'ROMA_humidity', 'ROMA_pressure', 'ROMA_sunshine', 'ROMA_temp_mean',
                        'TOURS_wind_speed', 'TOURS_humidity', 'TOURS_pressure', 'TOURS_global_radiation', 'TOURS_precipitation', 'TOURS_temp_mean', 'TOURS_temp_min', 'TOURS_temp_max'], axis=1)

In [11]:
# Check the pleasant dataset
prediction.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [12]:
prediction.shape

(22950, 16)

In [13]:
unscaled.isnull().sum()

DATE                   0
MONTH                  0
BASEL_cloud_cover      0
BASEL_wind_speed       0
BASEL_humidity         0
                      ..
VALENTIA_snow_depth    0
VALENTIA_sunshine      0
VALENTIA_temp_mean     0
VALENTIA_temp_min      0
VALENTIA_temp_max      0
Length: 149, dtype: int64

In [14]:
prediction.isnull().sum()

DATE                           0
BASEL_pleasant_weather         0
BELGRADE_pleasant_weather      0
BUDAPEST_pleasant_weather      0
DEBILT_pleasant_weather        0
DUSSELDORF_pleasant_weather    0
HEATHROW_pleasant_weather      0
KASSEL_pleasant_weather        0
LJUBLJANA_pleasant_weather     0
MAASTRICHT_pleasant_weather    0
MADRID_pleasant_weather        0
MUNCHENB_pleasant_weather      0
OSLO_pleasant_weather          0
SONNBLICK_pleasant_weather     0
STOCKHOLM_pleasant_weather     0
VALENTIA_pleasant_weather      0
dtype: int64

In [15]:
# Extract the different observation types

observation_types = ['cloud_cover', 'wind_speed', 'humidity', 'pressure',
                     'global_radiation', 'precipitation', 'snow_depth', 
                     'sunshine', 'temp_mean', 'temp_min', 'temp_max']

In [16]:
# Create a dictionary to store the count of stations for each observation type
station_counts = {}

for obs in observation_types:
    # Select columns related to the current observation type
    columns = [col for col in unscaled.columns if col.endswith(obs)]
    
    # Count the number of stations (i.e., the number of columns) for the current observation type
    station_counts[obs] = len(columns)

# Print the count of stations for each observation type
print("Number of stations covered by each observation type:")
for obs, count in station_counts.items():
    print(f"{obs}: {count} stations")

Number of stations covered by each observation type:
cloud_cover: 14 stations
wind_speed: 9 stations
humidity: 14 stations
pressure: 14 stations
global_radiation: 15 stations
precipitation: 15 stations
snow_depth: 6 stations
sunshine: 15 stations
temp_mean: 15 stations
temp_min: 15 stations
temp_max: 15 stations

### As we can see that wind-speed and snow_depth have missing values so, it's better to drop those values.

In [18]:
# Get a list of columns containing 'wind_speed' or 'snow_depth'
cols_to_drop = [col for col in unscaled.columns if '_wind_speed' in col or '_snow_depth' in col]

# Drop the columns
unscaled = unscaled.drop(cols_to_drop, axis=1)

In [19]:
unscaled.shape

(22950, 134)

In [20]:
# Find the stations with the above entries missing
# Get all column names
all_columns = unscaled.columns.tolist()
# Exclude 'DATE' and 'MONTH' columns
all_columns = [col for col in all_columns if col not in ['DATE', 'MONTH']]  
# Extract unique weather station names
weather_stations = set()  # Use a set to automatically store only unique values
for col in all_columns:
    station_name = col.split('_')[0]  # Split the column name at the underscore and take the first part
    weather_stations.add(station_name)

# Print the list of weather stations
print(weather_stations)

{'MUNCHENB', 'DEBILT', 'STOCKHOLM', 'BASEL', 'BELGRADE', 'HEATHROW', 'BUDAPEST', 'LJUBLJANA', 'MADRID', 'SONNBLICK', 'MAASTRICHT', 'OSLO', 'KASSEL', 'VALENTIA', 'DUSSELDORF'}

In [21]:
# Find stations missing observation types
observation_types = ['cloud_cover', 'humidity', 'pressure']

missing_stations_by_observation = {}

for obs in observation_types:
    # Select columns related to the current observation type
    columns = [col for col in unscaled.columns if col.endswith(obs)]
    
    # Extract station names by removing the observation type from the column names
    station_names = set([col.replace(f'_{obs}', '') for col in columns])
    
    # Identify stations that are in all_stations but missing from the current observation type
    missing_stations = weather_stations - station_names
    
    # Store the missing station names in the dictionary
    missing_stations_by_observation[obs] = missing_stations

# Print the missing station names for each observation type
for obs, missing_stations in missing_stations_by_observation.items():
    print(f"\nStations missing from {obs}:")
    if missing_stations:
        for station in missing_stations:
            print(station)
    else:
        print("None")

Stations missing from cloud_cover:
KASSEL

Stations missing from humidity:
STOCKHOLM

Stations missing from pressure:
MUNCHENB

In [22]:
unscaled.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,...,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,...,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,19600102,1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,...,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,19600103,1,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,...,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,19600104,1,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,...,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,19600105,1,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,...,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [23]:
# Cloud cover is the start of a stations data, Kassel is next to Heathrow, find the position of Heathrow_temp_max for the insertion of Kassel_cloud_cover
unscaled.columns.get_loc('HEATHROW_temp_max')

55

In [24]:
# Find the position for insertion of Stockholm humidity
unscaled.columns.get_loc('STOCKHOLM_cloud_cover') #humidity is 1 after cloud cover so (result +1)

117

In [25]:
# Find position for Munchenb pressure
unscaled.columns.get_loc('MUNCHENB_cloud_cover') # pressure is 2 after cloud cover so (result +2)

91

In [26]:
# Insert new columns into "unscaled" at specific positions.
# The data for these new columns is taken from weather stations they are close to

unscaled.insert(56,'KASSEL_cloud_cover', unscaled['DUSSELDORF_cloud_cover'])
unscaled.insert(119, 'STOCKHOLM_humidity', unscaled['OSLO_humidity'])
unscaled.insert(94,'MUNCHENB_pressure',unscaled['BASEL_pressure'])

In [27]:
unscaled.columns.tolist()

['DATE',
 'MONTH',
 'BASEL_cloud_cover',
 'BASEL_humidity',
 'BASEL_pressure',
 'BASEL_global_radiation',
 'BASEL_precipitation',
 'BASEL_sunshine',
 'BASEL_temp_mean',
 'BASEL_temp_min',
 'BASEL_temp_max',
 'BELGRADE_cloud_cover',
 'BELGRADE_humidity',
 'BELGRADE_pressure',
 'BELGRADE_global_radiation',
 'BELGRADE_precipitation',
 'BELGRADE_sunshine',
 'BELGRADE_temp_mean',
 'BELGRADE_temp_min',
 'BELGRADE_temp_max',
 'BUDAPEST_cloud_cover',
 'BUDAPEST_humidity',
 'BUDAPEST_pressure',
 'BUDAPEST_global_radiation',
 'BUDAPEST_precipitation',
 'BUDAPEST_sunshine',
 'BUDAPEST_temp_mean',
 'BUDAPEST_temp_min',
 'BUDAPEST_temp_max',
 'DEBILT_cloud_cover',
 'DEBILT_humidity',
 'DEBILT_pressure',
 'DEBILT_global_radiation',
 'DEBILT_precipitation',
 'DEBILT_sunshine',
 'DEBILT_temp_mean',
 'DEBILT_temp_min',
 'DEBILT_temp_max',
 'DUSSELDORF_cloud_cover',
 'DUSSELDORF_humidity',
 'DUSSELDORF_pressure',
 'DUSSELDORF_global_radiation',
 'DUSSELDORF_precipitation',
 'DUSSELDORF_sunshine',
 'DUSSELDORF_temp_mean',
 'DUSSELDORF_temp_min',
 'DUSSELDORF_temp_max',
 'HEATHROW_cloud_cover',
 'HEATHROW_humidity',
 'HEATHROW_pressure',
 'HEATHROW_global_radiation',
 'HEATHROW_precipitation',
 'HEATHROW_sunshine',
 'HEATHROW_temp_mean',
 'HEATHROW_temp_min',
 'HEATHROW_temp_max',
 'KASSEL_cloud_cover',
 'KASSEL_humidity',
 'KASSEL_pressure',
 'KASSEL_global_radiation',
 'KASSEL_precipitation',
 'KASSEL_sunshine',
 'KASSEL_temp_mean',
 'KASSEL_temp_min',
 'KASSEL_temp_max',
 'LJUBLJANA_cloud_cover',
 'LJUBLJANA_humidity',
 'LJUBLJANA_pressure',
 'LJUBLJANA_global_radiation',
 'LJUBLJANA_precipitation',
 'LJUBLJANA_sunshine',
 'LJUBLJANA_temp_mean',
 'LJUBLJANA_temp_min',
 'LJUBLJANA_temp_max',
 'MAASTRICHT_cloud_cover',
 'MAASTRICHT_humidity',
 'MAASTRICHT_pressure',
 'MAASTRICHT_global_radiation',
 'MAASTRICHT_precipitation',
 'MAASTRICHT_sunshine',
 'MAASTRICHT_temp_mean',
 'MAASTRICHT_temp_min',
 'MAASTRICHT_temp_max',
 'MADRID_cloud_cover',
 'MADRID_humidity',
 'MADRID_pressure',
 'MADRID_global_radiation',
 'MADRID_precipitation',
 'MADRID_sunshine',
 'MADRID_temp_mean',
 'MADRID_temp_min',
 'MADRID_temp_max',
 'MUNCHENB_cloud_cover',
 'MUNCHENB_humidity',
 'MUNCHENB_pressure',
 'MUNCHENB_global_radiation',
 'MUNCHENB_precipitation',
 'MUNCHENB_sunshine',
 'MUNCHENB_temp_mean',
 'MUNCHENB_temp_min',
 'MUNCHENB_temp_max',
 'OSLO_cloud_cover',
 'OSLO_humidity',
 'OSLO_pressure',
 'OSLO_global_radiation',
 'OSLO_precipitation',
 'OSLO_sunshine',
 'OSLO_temp_mean',
 'OSLO_temp_min',
 'OSLO_temp_max',
 'SONNBLICK_cloud_cover',
 'SONNBLICK_humidity',
 'SONNBLICK_pressure',
 'SONNBLICK_global_radiation',
 'SONNBLICK_precipitation',
 'SONNBLICK_sunshine',
 'SONNBLICK_temp_mean',
 'SONNBLICK_temp_min',
 'SONNBLICK_temp_max',
 'STOCKHOLM_cloud_cover',
 'STOCKHOLM_humidity',
 'STOCKHOLM_pressure',
 'STOCKHOLM_global_radiation',
 'STOCKHOLM_precipitation',
 'STOCKHOLM_sunshine',
 'STOCKHOLM_temp_mean',
 'STOCKHOLM_temp_min',
 'STOCKHOLM_temp_max',
 'VALENTIA_cloud_cover',
 'VALENTIA_humidity',
 'VALENTIA_pressure',
 'VALENTIA_global_radiation',
 'VALENTIA_precipitation',
 'VALENTIA_sunshine',
 'VALENTIA_temp_mean',
 'VALENTIA_temp_min',
 'VALENTIA_temp_max']

In [188]:
unscaled.head()

,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,...,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,...,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,...,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,...,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,...,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,...,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [182]:
prediction.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [184]:
# drop unneeded column from second dataset
prediction.drop(columns = 'DATE', inplace = True)

In [186]:
# Now, confirm drop
prediction.head()

,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [34]:
prediction.shape

(22950, 15)

## 3. Data Reshape

In [37]:
# Creat an 'X' matrix by reloading and naming our data 'X'
X = pd.read_csv(os.path.join(path,'weather_cleaned.csv'), index_col=False)

In [38]:
X.head()

,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,...,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,...,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,...,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,...,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,...,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,...,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [39]:
y = prediction

In [40]:
X.shape

(22950, 135)

In [41]:
# Turn X and y into arrays
X = np.array(X)
y = np.array(y)
X

array([[ 7.    ,  0.85  ,  1.018 , ...,  8.5   ,  6.    , 10.9   ],
       [ 6.    ,  0.84  ,  1.018 , ...,  8.9   ,  5.6   , 12.1   ],
       [ 8.    ,  0.9   ,  1.018 , ..., 10.5   ,  8.1   , 12.9   ],
       ...,
       [ 4.    ,  0.76  ,  1.0227, ..., 10.7   ,  7.9   , 13.5   ],
       [ 5.    ,  0.8   ,  1.0212, ..., 10.7   ,  7.9   , 13.5   ],
       [ 5.    ,  0.84  ,  1.0193, ..., 10.7   ,  7.9   , 13.5   ]])

In [42]:
X = X.reshape(-1,15,9)

In [43]:
# Verify Shape
X.shape

(22950, 15, 9)

In [44]:
# Verify Shape
y.shape

(22950, 15)

In [45]:
X

array([[[  7.    ,   0.85  ,   1.018 , ...,   6.5   ,   0.8   ,
          10.9   ],
        [  1.    ,   0.81  ,   1.0195, ...,   3.7   ,  -0.9   ,
           7.9   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.4   ,  -0.4   ,
           5.1   ],
        ...,
        [  4.    ,   0.73  ,   1.0304, ...,  -5.9   ,  -8.5   ,
          -3.2   ],
        [  5.    ,   0.98  ,   1.0114, ...,   4.2   ,   2.2   ,
           4.9   ],
        [  5.    ,   0.88  ,   1.0003, ...,   8.5   ,   6.    ,
          10.9   ]],

       [[  6.    ,   0.84  ,   1.018 , ...,   6.1   ,   3.3   ,
          10.1   ],
        [  6.    ,   0.84  ,   1.0172, ...,   2.9   ,   2.2   ,
           4.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.3   ,   1.4   ,
           3.1   ],
        ...,
        [  6.    ,   0.97  ,   1.0292, ...,  -9.5   , -10.5   ,
          -8.5   ],
        [  5.    ,   0.62  ,   1.0114, ...,   4.    ,   3.    ,
           5.    ],
        [  7.    ,   0.91  ,   1.0007, ...,   8.9   ,   5.6   ,
          12.1   ]],

       [[  8.    ,   0.9   ,   1.018 , ...,   8.5   ,   5.1   ,
           9.9   ],
        [  6.    ,   0.77  ,   1.0179, ...,   3.1   ,  -0.5   ,
           6.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.7   ,   1.7   ,
           5.3   ],
        ...,
        [  8.    ,   0.93  ,   1.032 , ...,  -9.5   , -10.    ,
          -8.9   ],
        [  5.    ,   0.69  ,   1.0114, ...,   2.4   ,   1.3   ,
           4.1   ],
        [  7.    ,   0.91  ,   1.0096, ...,  10.5   ,   8.1   ,
          12.9   ]],

       ...,

       [[  4.    ,   0.76  ,   1.0227, ...,  16.7   ,  13.1   ,
          22.4   ],
        [  2.    ,   0.68  ,   1.0278, ...,  13.4   ,   8.6   ,
          18.2   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  3.    ,   0.84  ,   1.0263, ...,   3.3   ,   2.1   ,
           4.5   ],
        [  5.    ,   0.85  ,   1.0059, ...,  13.1   ,  12.1   ,
          14.4   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]],

       [[  5.    ,   0.8   ,   1.0212, ...,  15.4   ,  11.6   ,
          21.1   ],
        [  1.    ,   0.68  ,   1.0238, ...,  15.    ,   9.1   ,
          20.9   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  3.    ,   0.84  ,   1.0263, ...,   3.4   ,   2.7   ,
           4.1   ],
        [  5.    ,   0.94  ,   1.016 , ...,   7.5   ,   5.1   ,
          12.4   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]],

       [[  5.    ,   0.84  ,   1.0193, ...,  13.5   ,   9.9   ,
          19.2   ],
        [  4.    ,   0.68  ,   1.0235, ...,  14.4   ,  10.4   ,
          18.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  4.    ,   0.84  ,   1.0263, ...,   1.7   ,   0.7   ,
           2.7   ],
        [  5.    ,   0.97  ,   1.0164, ...,   9.7   ,   5.    ,
          12.6   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]]])

## 4. Data Splitting

In [47]:
# Split data into train and test sets

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [48]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(17212, 15, 9) (17212, 15)
(5738, 15, 9) (5738, 15)

## 5. Keras Model

In [50]:
epochs = 30
batch_size = 16
n_hidden = 32

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='softmax')) # Options: sigmoid, tanh, softmax, relu

In [51]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 14, 32)         │           608 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 14, 16)         │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,831 (11.06 KB)

 Trainable params: 2,831 (11.06 KB)

 Non-trainable params: 0 (0.00 B)

## 6. Compile and Running Model

In [53]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [54]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 1s - 792us/step - accuracy: 0.1189 - loss: 5041.5273
Epoch 2/30
1076/1076 - 0s - 457us/step - accuracy: 0.1437 - loss: 54822.8867
Epoch 3/30
1076/1076 - 1s - 478us/step - accuracy: 0.1351 - loss: 177908.4531
Epoch 4/30
1076/1076 - 0s - 456us/step - accuracy: 0.1335 - loss: 381350.8125
Epoch 5/30
1076/1076 - 1s - 465us/step - accuracy: 0.1349 - loss: 663748.0625
Epoch 6/30
1076/1076 - 0s - 457us/step - accuracy: 0.1358 - loss: 1087406.3750
Epoch 7/30
1076/1076 - 0s - 459us/step - accuracy: 0.1306 - loss: 1571165.1250
Epoch 8/30
1076/1076 - 0s - 452us/step - accuracy: 0.1310 - loss: 2174751.0000
Epoch 9/30
1076/1076 - 0s - 440us/step - accuracy: 0.1337 - loss: 2933341.7500
Epoch 10/30
1076/1076 - 0s - 453us/step - accuracy: 0.1307 - loss: 3841698.5000
Epoch 11/30
1076/1076 - 1s - 466us/step - accuracy: 0.1318 - loss: 4917219.5000
Epoch 12/30
1076/1076 - 0s - 446us/step - accuracy: 0.1299 - loss: 6044450.5000
Epoch 13/30
1076/1076 - 0s - 445us/step - accuracy: 0.1324 - loss: 7433755.0000
Epoch 14/30
1076/1076 - 0s - 446us/step - accuracy: 0.1318 - loss: 8950011.0000
Epoch 15/30
1076/1076 - 0s - 445us/step - accuracy: 0.1297 - loss: 10705555.0000
Epoch 16/30
1076/1076 - 0s - 456us/step - accuracy: 0.1304 - loss: 12557534.0000
Epoch 17/30
1076/1076 - 0s - 464us/step - accuracy: 0.1310 - loss: 14778448.0000
Epoch 18/30
1076/1076 - 0s - 447us/step - accuracy: 0.1247 - loss: 17155950.0000
Epoch 19/30
1076/1076 - 0s - 447us/step - accuracy: 0.1268 - loss: 19607782.0000
Epoch 20/30
1076/1076 - 0s - 448us/step - accuracy: 0.1249 - loss: 22604680.0000
Epoch 21/30
1076/1076 - 0s - 446us/step - accuracy: 0.1311 - loss: 25526900.0000
Epoch 22/30
1076/1076 - 0s - 458us/step - accuracy: 0.1292 - loss: 28952656.0000
Epoch 23/30
1076/1076 - 0s - 454us/step - accuracy: 0.1254 - loss: 32517934.0000
Epoch 24/30
1076/1076 - 0s - 447us/step - accuracy: 0.1239 - loss: 36309668.0000
Epoch 25/30
1076/1076 - 0s - 437us/step - accuracy: 0.1259 - loss: 40749764.0000
Epoch 26/30
1076/1076 - 0s - 442us/step - accuracy: 0.1235 - loss: 45234276.0000
Epoch 27/30
1076/1076 - 0s - 441us/step - accuracy: 0.1219 - loss: 50016592.0000
Epoch 28/30
1076/1076 - 0s - 442us/step - accuracy: 0.1218 - loss: 55482160.0000
Epoch 29/30
1076/1076 - 0s - 443us/step - accuracy: 0.1224 - loss: 60565452.0000
Epoch 30/30
1076/1076 - 0s - 441us/step - accuracy: 0.1242 - loss: 66335796.0000

## 7. Confusion Matrix

In [56]:
# Define list of stations names

stations = {
0: 'BASEL',
1: 'BELGRADE',
2: 'BUDAPEST',
3: 'DEBILT',
4: 'DUSSELDORF',
5: 'HEATHROW',
6: 'KASSEL',
7: 'LJUBLJANA',
8: 'MAASTRICHT',
9: 'MADRID',
10: 'MUNCHENB',
11: 'OSLO',
12: 'SONNBLICK',
13: 'STOCKHOLM',
14: 'VALENTIA'

}

In [57]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [58]:
# Evaluate
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 407us/step
Pred        BASEL  BELGRADE  BUDAPEST  DEBILT  DUSSELDORF  HEATHROW  \
True
BASEL          84       617       143    1089          49        32
BELGRADE        0       246         1     234           0         0
BUDAPEST        0        27         0      61           0         0
DEBILT          0        11         0      38           0         0
DUSSELDORF      0         2         0      17           0         0
HEATHROW        0         1         0      41           0         0
KASSEL          0         3         0       3           0         0
LJUBLJANA       0        12         0      12           0         0
MAASTRICHT      0         2         0       3           0         0
MADRID          1        21         3     154           0         1
MUNCHENB        0         2         1       0           0         0
OSLO            0         0         0       3           0         0
STOCKHOLM       0         2         0       1           0         0
VALENTIA        0         0         0       1           0         0

Pred        LJUBLJANA  MAASTRICHT  MADRID  MUNCHENB  OSLO  SONNBLICK  \
True
BASEL              32          10    1491         3    52          8
BELGRADE            0           0     604         0     7          0
BUDAPEST            0           0     123         0     3          0
DEBILT              0           0      32         0     1          0
DUSSELDORF          0           0      10         0     0          0
HEATHROW            0           0      37         0     3          0
KASSEL              0           0       4         0     1          0
LJUBLJANA           0           0      37         0     0          0
MAASTRICHT          0           0       4         0     0          0
MADRID              0           0     266         0     9          0
MUNCHENB            0           0       4         0     1          0
OSLO                0           0       1         0     1          0
STOCKHOLM           0           0       1         0     0          0
VALENTIA            0           0       0         0     0          0

Pred        STOCKHOLM  VALENTIA
True
BASEL              37        35
BELGRADE            0         0
BUDAPEST            0         0
DEBILT              0         0
DUSSELDORF          0         0
HEATHROW            0         0
KASSEL              0         0
LJUBLJANA           0         0
MAASTRICHT          0         0
MADRID              3         0
MUNCHENB            0         0
OSLO                0         0
STOCKHOLM           0         0
VALENTIA            0         0

## 8. Keras Model Retrials

In [60]:
epochs = 30
batch_size = 16
n_hidden = 4

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='softmax')) # Options: sigmoid, tanh, softmax, relu

In [61]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_1 (Conv1D)               │ (None, 14, 4)          │            76 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 14, 16)         │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,851 (7.23 KB)

 Trainable params: 1,851 (7.23 KB)

 Non-trainable params: 0 (0.00 B)

In [62]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [63]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 1s - 752us/step - accuracy: 0.0937 - loss: 1019.3293
Epoch 2/30
1076/1076 - 1s - 475us/step - accuracy: 0.1070 - loss: 10213.6719
Epoch 3/30
1076/1076 - 1s - 478us/step - accuracy: 0.1063 - loss: 31015.3750
Epoch 4/30
1076/1076 - 1s - 475us/step - accuracy: 0.1036 - loss: 66385.6328
Epoch 5/30
1076/1076 - 1s - 475us/step - accuracy: 0.1117 - loss: 115120.7344
Epoch 6/30
1076/1076 - 1s - 477us/step - accuracy: 0.1068 - loss: 173339.8281
Epoch 7/30
1076/1076 - 1s - 475us/step - accuracy: 0.1120 - loss: 239406.6875
Epoch 8/30
1076/1076 - 1s - 475us/step - accuracy: 0.1099 - loss: 326464.5938
Epoch 9/30
1076/1076 - 1s - 476us/step - accuracy: 0.1109 - loss: 415324.8438
Epoch 10/30
1076/1076 - 1s - 475us/step - accuracy: 0.1073 - loss: 519697.1250
Epoch 11/30
1076/1076 - 1s - 486us/step - accuracy: 0.1109 - loss: 657036.3750
Epoch 12/30
1076/1076 - 1s - 496us/step - accuracy: 0.1108 - loss: 798894.7500
Epoch 13/30
1076/1076 - 0s - 433us/step - accuracy: 0.1121 - loss: 957990.5625
Epoch 14/30
1076/1076 - 0s - 429us/step - accuracy: 0.1078 - loss: 1133342.6250
Epoch 15/30
1076/1076 - 0s - 428us/step - accuracy: 0.1107 - loss: 1312564.5000
Epoch 16/30
1076/1076 - 0s - 429us/step - accuracy: 0.1136 - loss: 1524702.7500
Epoch 17/30
1076/1076 - 0s - 428us/step - accuracy: 0.1109 - loss: 1772631.8750
Epoch 18/30
1076/1076 - 0s - 428us/step - accuracy: 0.1113 - loss: 2052789.7500
Epoch 19/30
1076/1076 - 0s - 427us/step - accuracy: 0.1110 - loss: 2327715.0000
Epoch 20/30
1076/1076 - 0s - 431us/step - accuracy: 0.1122 - loss: 2593710.5000
Epoch 21/30
1076/1076 - 0s - 428us/step - accuracy: 0.1092 - loss: 2911278.2500
Epoch 22/30
1076/1076 - 0s - 430us/step - accuracy: 0.1148 - loss: 3269253.2500
Epoch 23/30
1076/1076 - 0s - 429us/step - accuracy: 0.1102 - loss: 3630174.7500
Epoch 24/30
1076/1076 - 0s - 428us/step - accuracy: 0.1142 - loss: 3991841.5000
Epoch 25/30
1076/1076 - 0s - 428us/step - accuracy: 0.1114 - loss: 4402854.5000
Epoch 26/30
1076/1076 - 0s - 429us/step - accuracy: 0.1138 - loss: 4893973.0000
Epoch 27/30
1076/1076 - 0s - 428us/step - accuracy: 0.1118 - loss: 5360778.5000
Epoch 28/30
1076/1076 - 0s - 427us/step - accuracy: 0.1124 - loss: 5926744.5000
Epoch 29/30
1076/1076 - 0s - 423us/step - accuracy: 0.1112 - loss: 6415041.0000
Epoch 30/30
1076/1076 - 0s - 425us/step - accuracy: 0.1094 - loss: 7014029.5000

In [64]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [65]:
# Evaluate

print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step
Pred        BASEL  BELGRADE  BUDAPEST  HEATHROW  KASSEL  LJUBLJANA  MADRID  \
True
BASEL           1        31         9      2193       3         10    1402
BELGRADE        0         3         0       463       0          0     626
BUDAPEST        0         1         0       106       0          0     107
DEBILT          0         0         0        65       0          0      17
DUSSELDORF      0         0         0        19       0          0      10
HEATHROW        0         0         0        65       0          0      17
KASSEL          0         0         0         8       0          0       3
LJUBLJANA       0         0         0        25       0          0      36
MAASTRICHT      0         0         0         7       0          0       2
MADRID          0         0         0       198       0          0     260
MUNCHENB        0         0         0         6       0          0       2
OSLO            0         0         0         3       0          0       2
STOCKHOLM       0         0         0         4       0          0       0
VALENTIA        0         0         0         1       0          0       0

Pred        MUNCHENB
True
BASEL             33
BELGRADE           0
BUDAPEST           0
DEBILT             0
DUSSELDORF         0
HEATHROW           0
KASSEL             0
LJUBLJANA          0
MAASTRICHT         0
MADRID             0
MUNCHENB           0
OSLO               0
STOCKHOLM          0
VALENTIA           0

### Softmax is not producing good results, try with tanh, sigmoid, and relu¶

In [67]:
epochs = 30
batch_size = 16
n_hidden = 128

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='tanh')) # Options: sigmoid, tanh, softmax, relu

In [68]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_2 (Conv1D)               │ (None, 14, 128)        │         2,432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 14, 16)         │         2,064 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,191 (24.18 KB)

 Trainable params: 6,191 (24.18 KB)

 Non-trainable params: 0 (0.00 B)

In [69]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [70]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 1s - 898us/step - accuracy: 0.0065 - loss: 23.5259
Epoch 2/30
1076/1076 - 1s - 672us/step - accuracy: 0.0071 - loss: 27.5346
Epoch 3/30
1076/1076 - 1s - 684us/step - accuracy: 0.0083 - loss: 27.7188
Epoch 4/30
1076/1076 - 1s - 740us/step - accuracy: 0.0106 - loss: 27.3695
Epoch 5/30
1076/1076 - 1s - 698us/step - accuracy: 0.0330 - loss: 21.9718
Epoch 6/30
1076/1076 - 1s - 687us/step - accuracy: 0.0332 - loss: 22.1207
Epoch 7/30
1076/1076 - 1s - 689us/step - accuracy: 0.0680 - loss: 26.3292
Epoch 8/30
1076/1076 - 1s - 697us/step - accuracy: 0.1141 - loss: 26.9696
Epoch 9/30
1076/1076 - 1s - 714us/step - accuracy: 0.1196 - loss: 26.9696
Epoch 10/30
1076/1076 - 1s - 715us/step - accuracy: 0.1200 - loss: 26.9696
Epoch 11/30
1076/1076 - 1s - 699us/step - accuracy: 0.1204 - loss: 26.9696
Epoch 12/30
1076/1076 - 1s - 686us/step - accuracy: 0.1207 - loss: 26.9696
Epoch 13/30
1076/1076 - 1s - 690us/step - accuracy: 0.1215 - loss: 26.9696
Epoch 14/30
1076/1076 - 1s - 701us/step - accuracy: 0.1224 - loss: 26.9696
Epoch 15/30
1076/1076 - 1s - 750us/step - accuracy: 0.1227 - loss: 26.9696
Epoch 16/30
1076/1076 - 1s - 729us/step - accuracy: 0.1232 - loss: 26.9696
Epoch 17/30
1076/1076 - 1s - 763us/step - accuracy: 0.1238 - loss: 26.9687
Epoch 18/30
1076/1076 - 1s - 775us/step - accuracy: 0.1243 - loss: 26.9687
Epoch 19/30
1076/1076 - 1s - 767us/step - accuracy: 0.1243 - loss: 26.9687
Epoch 20/30
1076/1076 - 1s - 726us/step - accuracy: 0.1243 - loss: 26.9687
Epoch 21/30
1076/1076 - 1s - 737us/step - accuracy: 0.1243 - loss: 26.9687
Epoch 22/30
1076/1076 - 1s - 682us/step - accuracy: 0.1243 - loss: 26.9686
Epoch 23/30
1076/1076 - 1s - 685us/step - accuracy: 0.1243 - loss: 26.9687
Epoch 24/30
1076/1076 - 1s - 669us/step - accuracy: 0.1243 - loss: 26.9687
Epoch 25/30
1076/1076 - 1s - 687us/step - accuracy: 0.1243 - loss: 26.9687
Epoch 26/30
1076/1076 - 1s - 692us/step - accuracy: 0.1243 - loss: 26.9687
Epoch 27/30
1076/1076 - 1s - 669us/step - accuracy: 0.1243 - loss: 26.9687
Epoch 28/30
1076/1076 - 1s - 674us/step - accuracy: 0.1243 - loss: 26.9687
Epoch 29/30
1076/1076 - 1s - 650us/step - accuracy: 0.1243 - loss: 26.9687
Epoch 30/30
1076/1076 - 1s - 706us/step - accuracy: 0.1243 - loss: 26.9687

In [71]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [72]:
# Evaluate

print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step
Pred        BELGRADE  HEATHROW  KASSEL  LJUBLJANA  OSLO  VALENTIA
True
BASEL           1805       136    1250        121     2       368
BELGRADE         672       204     124          2     4        86
BUDAPEST         136        38      22          0     0        18
DEBILT            70         9       1          0     1         1
DUSSELDORF        23         3       2          0     0         1
HEATHROW          56        13       7          0     0         6
KASSEL             9         1       1          0     0         0
LJUBLJANA         31        17       0          0     1        12
MAASTRICHT         5         0       3          0     0         1
MADRID           127        89      76          2     6       158
MUNCHENB           3         0       0          0     0         5
OSLO               4         1       0          0     0         0
STOCKHOLM          4         0       0          0     0         0
VALENTIA           1         0       0          0     0         0

### Model's loss is decreasing (which is good), but we're not seeing that improvement reflected in accuracy.

In [74]:
epochs = 30
batch_size = 16
n_hidden = 64

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='tanh')) # Options: sigmoid, tanh, softmax, relu

In [75]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_3 (Conv1D)               │ (None, 14, 64)         │         1,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 14, 16)         │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,951 (15.43 KB)

 Trainable params: 3,951 (15.43 KB)

 Non-trainable params: 0 (0.00 B)

In [76]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [77]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 1s - 957us/step - accuracy: 0.0188 - loss: 23.9314
Epoch 2/30
1076/1076 - 1s - 618us/step - accuracy: 0.0440 - loss: 24.6342
Epoch 3/30
1076/1076 - 1s - 623us/step - accuracy: 0.0494 - loss: 26.3881
Epoch 4/30
1076/1076 - 1s - 626us/step - accuracy: 0.0587 - loss: 26.8910
Epoch 5/30
1076/1076 - 1s - 620us/step - accuracy: 0.0627 - loss: 26.9181
Epoch 6/30
1076/1076 - 1s - 608us/step - accuracy: 0.0657 - loss: 26.9293
Epoch 7/30
1076/1076 - 1s - 623us/step - accuracy: 0.0686 - loss: 26.9415
Epoch 8/30
1076/1076 - 1s - 621us/step - accuracy: 0.0710 - loss: 26.9593
Epoch 9/30
1076/1076 - 1s - 620us/step - accuracy: 0.0746 - loss: 26.9649
Epoch 10/30
1076/1076 - 1s - 629us/step - accuracy: 0.0801 - loss: 26.9864
Epoch 11/30
1076/1076 - 1s - 618us/step - accuracy: 0.0833 - loss: 26.9865
Epoch 12/30
1076/1076 - 1s - 624us/step - accuracy: 0.0863 - loss: 26.9855
Epoch 13/30
1076/1076 - 1s - 627us/step - accuracy: 0.0914 - loss: 26.9968
Epoch 14/30
1076/1076 - 1s - 619us/step - accuracy: 0.0953 - loss: 27.0033
Epoch 15/30
1076/1076 - 1s - 626us/step - accuracy: 0.0966 - loss: 27.0033
Epoch 16/30
1076/1076 - 1s - 627us/step - accuracy: 0.0968 - loss: 27.0033
Epoch 17/30
1076/1076 - 1s - 624us/step - accuracy: 0.0968 - loss: 27.0033
Epoch 18/30
1076/1076 - 1s - 621us/step - accuracy: 0.0968 - loss: 27.0033
Epoch 19/30
1076/1076 - 1s - 625us/step - accuracy: 0.0968 - loss: 27.0033
Epoch 20/30
1076/1076 - 1s - 626us/step - accuracy: 0.0968 - loss: 27.0033
Epoch 21/30
1076/1076 - 1s - 622us/step - accuracy: 0.0968 - loss: 27.0033
Epoch 22/30
1076/1076 - 1s - 630us/step - accuracy: 0.0968 - loss: 27.0033
Epoch 23/30
1076/1076 - 1s - 639us/step - accuracy: 0.0968 - loss: 27.0033
Epoch 24/30
1076/1076 - 1s - 681us/step - accuracy: 0.0968 - loss: 27.0033
Epoch 25/30
1076/1076 - 1s - 629us/step - accuracy: 0.0968 - loss: 27.0033
Epoch 26/30
1076/1076 - 1s - 626us/step - accuracy: 0.0968 - loss: 27.0033
Epoch 27/30
1076/1076 - 1s - 624us/step - accuracy: 0.0968 - loss: 27.0033
Epoch 28/30
1076/1076 - 1s - 683us/step - accuracy: 0.0968 - loss: 27.0033
Epoch 29/30
1076/1076 - 1s - 631us/step - accuracy: 0.0968 - loss: 27.0033
Epoch 30/30
1076/1076 - 1s - 628us/step - accuracy: 0.0968 - loss: 27.0033

In [78]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [163]:
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 265us/step
Pred        BASEL
True
BASEL        3682
BELGRADE     1092
BUDAPEST      214
DEBILT         82
DUSSELDORF     29
HEATHROW       82
KASSEL         11
LJUBLJANA      61
MAASTRICHT      9
MADRID        458
MUNCHENB        8
OSLO            5
STOCKHOLM       4
VALENTIA        1

### This means:
### 1. Loss is stable, not low
### 2. Accuracy is much higher now, which is a good sign
### 3. Trying out ReLU and Sigmoid activations

In [81]:
epochs = 30
batch_size = 16
n_hidden = 64

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='sigmoid')) # Options: sigmoid, tanh, softmax, relu

In [82]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_4 (Conv1D)               │ (None, 14, 64)         │         1,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 14, 16)         │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_4 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_4 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,951 (15.43 KB)

 Trainable params: 3,951 (15.43 KB)

 Non-trainable params: 0 (0.00 B)

In [83]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [84]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 1s - 873us/step - accuracy: 0.6204 - loss: 13304.8057
Epoch 2/30
1076/1076 - 1s - 656us/step - accuracy: 0.6417 - loss: 135769.8750
Epoch 3/30
1076/1076 - 1s - 606us/step - accuracy: 0.6425 - loss: 450884.8750
Epoch 4/30
1076/1076 - 1s - 612us/step - accuracy: 0.6434 - loss: 1020033.4375
Epoch 5/30
1076/1076 - 1s - 668us/step - accuracy: 0.6436 - loss: 1774642.7500
Epoch 6/30
1076/1076 - 1s - 607us/step - accuracy: 0.6437 - loss: 2740125.7500
Epoch 7/30
1076/1076 - 1s - 602us/step - accuracy: 0.6437 - loss: 3997154.2500
Epoch 8/30
1076/1076 - 1s - 596us/step - accuracy: 0.6437 - loss: 5500255.0000
Epoch 9/30
1076/1076 - 1s - 600us/step - accuracy: 0.6437 - loss: 7375086.5000
Epoch 10/30
1076/1076 - 1s - 601us/step - accuracy: 0.6437 - loss: 9436835.0000
Epoch 11/30
1076/1076 - 1s - 631us/step - accuracy: 0.6437 - loss: 11800229.0000
Epoch 12/30
1076/1076 - 1s - 605us/step - accuracy: 0.6437 - loss: 14635115.0000
Epoch 13/30
1076/1076 - 1s - 607us/step - accuracy: 0.6437 - loss: 17662088.0000
Epoch 14/30
1076/1076 - 1s - 604us/step - accuracy: 0.6436 - loss: 21323060.0000
Epoch 15/30
1076/1076 - 1s - 610us/step - accuracy: 0.6437 - loss: 25263804.0000
Epoch 16/30
1076/1076 - 1s - 610us/step - accuracy: 0.6437 - loss: 29767698.0000
Epoch 17/30
1076/1076 - 1s - 659us/step - accuracy: 0.6437 - loss: 34751136.0000
Epoch 18/30
1076/1076 - 1s - 624us/step - accuracy: 0.6437 - loss: 40044100.0000
Epoch 19/30
1076/1076 - 1s - 595us/step - accuracy: 0.6437 - loss: 45952924.0000
Epoch 20/30
1076/1076 - 1s - 596us/step - accuracy: 0.6437 - loss: 52465212.0000
Epoch 21/30
1076/1076 - 1s - 620us/step - accuracy: 0.6437 - loss: 59954296.0000
Epoch 22/30
1076/1076 - 1s - 599us/step - accuracy: 0.6437 - loss: 67325456.0000
Epoch 23/30
1076/1076 - 1s - 620us/step - accuracy: 0.6437 - loss: 75215592.0000
Epoch 24/30
1076/1076 - 1s - 602us/step - accuracy: 0.6437 - loss: 84011808.0000
Epoch 25/30
1076/1076 - 1s - 599us/step - accuracy: 0.6437 - loss: 94029984.0000
Epoch 26/30
1076/1076 - 1s - 619us/step - accuracy: 0.6437 - loss: 104174208.0000
Epoch 27/30
1076/1076 - 1s - 640us/step - accuracy: 0.6437 - loss: 114645080.0000
Epoch 28/30
1076/1076 - 1s - 612us/step - accuracy: 0.6437 - loss: 126109400.0000
Epoch 29/30
1076/1076 - 1s - 585us/step - accuracy: 0.6437 - loss: 139578752.0000
Epoch 30/30
1076/1076 - 1s - 621us/step - accuracy: 0.6437 - loss: 152196736.0000

In [85]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [86]:
# Evaluate

print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step
Pred        BASEL  VALENTIA
True
BASEL        3679         3
BELGRADE     1092         0
BUDAPEST      214         0
DEBILT         82         0
DUSSELDORF     29         0
HEATHROW       82         0
KASSEL         11         0
LJUBLJANA      61         0
MAASTRICHT      9         0
MADRID        458         0
MUNCHENB        8         0
OSLO            5         0
STOCKHOLM       4         0
VALENTIA        1         0

### When I use tanh, I get much better loss and accuracy. But when I switch to ReLU, both get worse. Still, I want to give ReLU another shot and see if I can make it work.

In [88]:
epochs = 15
batch_size = 4
n_hidden = 4

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='relu')) # Options: sigmoid, tanh, softmax, relu

In [89]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_5 (Conv1D)               │ (None, 14, 4)          │            76 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 14, 16)         │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_5 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_5 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,851 (7.23 KB)

 Trainable params: 1,851 (7.23 KB)

 Non-trainable params: 0 (0.00 B)

In [90]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [91]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/15
4303/4303 - 2s - 489us/step - accuracy: 0.0919 - loss: 18.4190
Epoch 2/15
4303/4303 - 2s - 384us/step - accuracy: 0.0906 - loss: 17.8615
Epoch 3/15
4303/4303 - 2s - 384us/step - accuracy: 0.0840 - loss: 17.3831
Epoch 4/15
4303/4303 - 2s - 393us/step - accuracy: 0.3812 - loss: nan
Epoch 5/15
4303/4303 - 2s - 380us/step - accuracy: 0.6440 - loss: nan
Epoch 6/15
4303/4303 - 2s - 374us/step - accuracy: 0.6440 - loss: nan
Epoch 7/15
4303/4303 - 2s - 376us/step - accuracy: 0.6440 - loss: nan
Epoch 8/15
4303/4303 - 2s - 374us/step - accuracy: 0.6440 - loss: nan
Epoch 9/15
4303/4303 - 2s - 374us/step - accuracy: 0.6440 - loss: nan
Epoch 10/15
4303/4303 - 2s - 375us/step - accuracy: 0.6440 - loss: nan
Epoch 11/15
4303/4303 - 2s - 375us/step - accuracy: 0.6440 - loss: nan
Epoch 12/15
4303/4303 - 2s - 375us/step - accuracy: 0.6440 - loss: nan
Epoch 13/15
4303/4303 - 2s - 375us/step - accuracy: 0.6440 - loss: nan
Epoch 14/15
4303/4303 - 2s - 376us/step - accuracy: 0.6440 - loss: nan
Epoch 15/15
4303/4303 - 2s - 375us/step - accuracy: 0.6440 - loss: nan

In [92]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [93]:
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step
Pred        BASEL
True
BASEL        3682
BELGRADE     1092
BUDAPEST      214
DEBILT         82
DUSSELDORF     29
HEATHROW       82
KASSEL         11
LJUBLJANA      61
MAASTRICHT      9
MADRID        458
MUNCHENB        8
OSLO            5
STOCKHOLM       4
VALENTIA        1