# ClimateWins Weather Prediction : Keras Layered Model (RNN/LSTM)

## This script contains:
### 1. Import Libraries and Data
### 2. Data Wrangling
### 3. Split the Data
### 4. Keras Model 
### 5. Compiling and Running Model
### 6. Confusion Matrix 
### 7. Keras Model Retrials (Until Convergence)

## 1. Import Libraries and Data

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import operator
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from numpy import unique
from numpy import reshape
from keras.models import Sequential
from keras.layers import Conv1D, Conv2D, Dense, BatchNormalization, Flatten, MaxPooling1D, Dropout
from keras.layers import LSTM
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import warnings
warnings.filterwarnings("ignore")

In [6]:
# Set display options to show all columns

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [8]:
# Create path for faster data importation
# Create a path for faster data importation
path = r'/Users/amritkaur/Desktop/CAREERFOUNDRY/Machine Learning/Achievement 2/Data Sets'

In [10]:
X = pd.read_csv(os.path.join(path, 'weather_cleaned.csv'))
prediction = pd.read_csv(os.path.join(path, 'Dataset-Answers-Weather_Prediction_Pleasant_Weather.csv'))
X.head()

,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,BELGRADE_humidity,BELGRADE_pressure,BELGRADE_global_radiation,BELGRADE_precipitation,BELGRADE_sunshine,BELGRADE_temp_mean,BELGRADE_temp_min,BELGRADE_temp_max,BUDAPEST_cloud_cover,BUDAPEST_humidity,BUDAPEST_pressure,BUDAPEST_global_radiation,BUDAPEST_precipitation,BUDAPEST_sunshine,BUDAPEST_temp_mean,BUDAPEST_temp_min,BUDAPEST_temp_max,DEBILT_cloud_cover,DEBILT_humidity,DEBILT_pressure,DEBILT_global_radiation,DEBILT_precipitation,DEBILT_sunshine,DEBILT_temp_mean,DEBILT_temp_min,DEBILT_temp_max,DUSSELDORF_cloud_cover,DUSSELDORF_humidity,DUSSELDORF_pressure,DUSSELDORF_global_radiation,DUSSELDORF_precipitation,DUSSELDORF_sunshine,DUSSELDORF_temp_mean,DUSSELDORF_temp_min,DUSSELDORF_temp_max,HEATHROW_cloud_cover,HEATHROW_humidity,HEATHROW_pressure,HEATHROW_global_radiation,HEATHROW_precipitation,HEATHROW_sunshine,HEATHROW_temp_mean,HEATHROW_temp_min,HEATHROW_temp_max,KASSEL_cloud_cover,KASSEL_humidity,KASSEL_pressure,KASSEL_global_radiation,KASSEL_precipitation,KASSEL_sunshine,KASSEL_temp_mean,KASSEL_temp_min,KASSEL_temp_max,LJUBLJANA_cloud_cover,LJUBLJANA_humidity,LJUBLJANA_pressure,LJUBLJANA_global_radiation,LJUBLJANA_precipitation,LJUBLJANA_sunshine,LJUBLJANA_temp_mean,LJUBLJANA_temp_min,LJUBLJANA_temp_max,MAASTRICHT_cloud_cover,MAASTRICHT_humidity,MAASTRICHT_pressure,MAASTRICHT_global_radiation,MAASTRICHT_precipitation,MAASTRICHT_sunshine,MAASTRICHT_temp_mean,MAASTRICHT_temp_min,MAASTRICHT_temp_max,MADRID_cloud_cover,MADRID_humidity,MADRID_pressure,MADRID_global_radiation,MADRID_precipitation,MADRID_sunshine,MADRID_temp_mean,MADRID_temp_min,MADRID_temp_max,MUNCHENB_cloud_cover,MUNCHENB_humidity,MUNCHENB_pressure,MUNCHENB_global_radiation,MUNCHENB_precipitation,MUNCHENB_sunshine,MUNCHENB_temp_mean,MUNCHENB_temp_min,MUNCHENB_temp_max,OSLO_cloud_cover,OSLO_humidity,OSLO_pressure,OSLO_global_radiation,OSLO_precipitation,OSLO_sunshine,OSLO_temp_mean,OSLO_temp_min,OSLO_temp_max,SONNBLICK_cloud_cover,SONNBLICK_humidity,SONNBLICK_pressure,SONNBLICK_global_radiation,SONNBLICK_precipitation,SONNBLICK_sunshine,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,STOCKHOLM_cloud_cover,STOCKHOLM_humidity,STOCKHOLM_pressure,STOCKHOLM_global_radiation,STOCKHOLM_precipitation,STOCKHOLM_sunshine,STOCKHOLM_temp_mean,STOCKHOLM_temp_min,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,0.81,1.0195,0.88,0.00,7.0,3.7,-0.9,7.9,4,0.67,1.017,0.44,0.01,2.3,2.4,-0.4,5.1,7,0.85,1.0032,0.07,0.25,0.0,9.3,7.4,11.0,8,0.83,1.0161,0.12,0.08,0.0,10.0,7.0,11.5,7,0.91,1.0010,0.13,0.22,0.0,10.6,9.4,8.3,8,0.82,1.0094,0.28,0.48,1.6,7.9,3.9,9.4,8,1.00,1.0173,0.20,0.00,0.0,-0.6,-1.9,0.5,7,0.83,1.0063,0.22,0.32,1.0,9.5,8.5,11.1,6,0.92,1.0260,0.53,0.0,1.4,7.6,4.4,10.8,5,0.67,1.018,0.20,0.10,0.0,6.9,1.1,10.4,8,0.98,0.9978,0.04,1.14,0.0,4.9,3.8,5.9,4,0.73,1.0304,0.48,0.01,2.3,-5.9,-8.5,-3.2,5,0.98,1.0114,0.05,0.32,0.0,4.2,2.2,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,0.84,1.0172,0.25,0.00,0.0,2.9,2.2,4.4,4,0.67,1.017,0.18,0.31,0.0,2.3,1.4,3.1,8,0.90,1.0056,0.14,0.06,0.1,7.7,6.4,8.3,8,0.89,1.0161,0.18,0.66,0.5,8.2,7.4,11.0,7,0.98,1.0051,0.13,0.23,0.0,6.1,3.9,10.6,8,0.86,1.0086,0.12,0.27,0.0,7.7,6.8,9.1,6,0.94,1.0173,0.56,0.13,3.2,2.1,-1.3,5.5,8,0.92,1.0062,0.17,1.34,0.4,8.6,7.5,9.9,7,0.86,1.0254,0.46,0.0,0.9,9.8,7.4,12.2,6,0.72,1.018,0.61,0.30,5.1,6.2,4.2,10.2,8,0.62,1.0139,0.04,0.00,0.0,3.4,2.8,4.9,6,0.97,1.0292,0.21,0.61,0.0,-9.5,-10.5,-8.5,5,0.62,1.0114,0.05,0.06,0.0,4.0,3.0,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,0.77,1.0179,0.67,0.00,3.5,3.1,-0.5,6.4,4,0.67,1.017,0.30,0.00,0.6,2.7,1.7,5.3,6,0.92,1.0165,0.28,0.01,3.0,6.8,4.6,9.9,7,0.95,1.0161,0.12,0.07,0.0,7.1,6.9,9.1,8,0.96,1.0166,0.15,0.07,0.1,8.4,6.1,12.2,7,0.91,1.0129,0.12,0.60,0.0,6.5,6.0,8.0,8,0.96,1.0173,0.20,0.12,0.0,4.6,0.9,6.3,7,0.97,1.0167,0.12,0.46,0.0,6.9,5.5,9.9,5,0.90,1.0287,0.63,0.0,2.3,8.6,6.4,10.8,6,0.91,1.018,0.20,0.30,0.0,5.8,4.0,8.0,8,0.69,1.0234,0.04,0.08,0.0,1.9,0.6,3.1,8,0.93,1.0320,0.21,3.20,0.0,-9.5,-10.0,-8.9,5,0.69,1.0114,0.05,0.02,0.0,2.4,1.3,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,0.93,1.0268,0.25,0.00,0.0,2.0,-2.0,3.0,4,0.67,1.017,0.19,0.00,0.0,2.0,0.4,4.4,8,0.95,1.0265,0.08,0.09,0.0,6.7,3.6,10.1,8,0.86,1.0161,0.12,0.02,0.0,6.8,3.6,8.0,8,0.98,1.0230,0.13,0.00,0.0,9.4,6.7,8.9,8,0.87,1.0290,0.12,0.00,0.0,5.8,5.2,6.5,6,0.94,1.0173,0.49,0.00,2.2,3.2,1.0,7.0,7,0.89,1.0277,0.16,0.00,0.3,7.0,3.0,10.0,0,0.75,1.0281,1.16,0.0,8.7,10.3,4.5,16.1,6,0.90,1.018,0.20,0.01,0.0,3.9,3.2,5.4,8,0.98,1.0244,0.04,0.35,0.0,3.0,0.4,4.9,5,0.93,1.0443,0.22,1.10,0.0,-11.5,-12.9,-10.0,5,0.98,1.0114,0.05,0.00,0.0,1.2,0.4,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,0.99,1.0286,0.25,0.06,0.0,2.0,0.7,2.8,4,0.67,1.017,0.19,0.00,0.0,2.5,1.1,5.3,6,0.90,1.0243,0.04,0.39,0.0,8.0,2.4,11.2,7,0.92,1.0161,0.12,0.62,0.0,7.7,6.2,11.0,5,0.84,1.0275,0.30,0.00,2.1,8.9,8.9,7.2,7,0.86,1.0262,0.13,0.71,0.0,5.4,3.7,6.0,7,0.94,1.0173,0.20,0.00,0.0,3.6,0.4,4.8,7,0.92,1.0259,0.12,0.56,0.0,8.1,2.5,11.1,2,0.64,1.0269,1.10,0.0,7.8,12.1,8.2,16.0,5,0.85,1.018,0.65,0.96,5.6,1.8,-3.0,6.0,8,0.96,1.0092,0.05,0.26,0.0,3.7,2.9,4.9,2,0.75,1.0430,0.72,0.01,6.1,-9.3,-12.0,-6.5,5,0.96,1.0114,0.05,1.32,0.0,3.3,0.8,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [12]:
X.shape

(22950, 135)

In [14]:
prediction.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [16]:
prediction.shape

(22950, 16)

## 2. Data Wrangling

In [19]:
# Drop DATE column from answers

prediction.drop(columns = 'DATE', inplace = True)

In [21]:
prediction.shape

(22950, 15)

In [23]:
y = prediction

In [25]:
X.shape

(22950, 135)

In [27]:
# Turn X and y into arrays
X = np.array(X)
y = np.array(y)
X

array([[ 7.    ,  0.85  ,  1.018 , ...,  8.5   ,  6.    , 10.9   ],
       [ 6.    ,  0.84  ,  1.018 , ...,  8.9   ,  5.6   , 12.1   ],
       [ 8.    ,  0.9   ,  1.018 , ..., 10.5   ,  8.1   , 12.9   ],
       ...,
       [ 4.    ,  0.76  ,  1.0227, ..., 10.7   ,  7.9   , 13.5   ],
       [ 5.    ,  0.8   ,  1.0212, ..., 10.7   ,  7.9   , 13.5   ],
       [ 5.    ,  0.84  ,  1.0193, ..., 10.7   ,  7.9   , 13.5   ]])

In [29]:
X = X.reshape(-1,15,9)

In [31]:
X.shape

(22950, 15, 9)

In [33]:
y.shape

(22950, 15)

In [35]:
X

array([[[  7.    ,   0.85  ,   1.018 , ...,   6.5   ,   0.8   ,
          10.9   ],
        [  1.    ,   0.81  ,   1.0195, ...,   3.7   ,  -0.9   ,
           7.9   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.4   ,  -0.4   ,
           5.1   ],
        ...,
        [  4.    ,   0.73  ,   1.0304, ...,  -5.9   ,  -8.5   ,
          -3.2   ],
        [  5.    ,   0.98  ,   1.0114, ...,   4.2   ,   2.2   ,
           4.9   ],
        [  5.    ,   0.88  ,   1.0003, ...,   8.5   ,   6.    ,
          10.9   ]],

       [[  6.    ,   0.84  ,   1.018 , ...,   6.1   ,   3.3   ,
          10.1   ],
        [  6.    ,   0.84  ,   1.0172, ...,   2.9   ,   2.2   ,
           4.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.3   ,   1.4   ,
           3.1   ],
        ...,
        [  6.    ,   0.97  ,   1.0292, ...,  -9.5   , -10.5   ,
          -8.5   ],
        [  5.    ,   0.62  ,   1.0114, ...,   4.    ,   3.    ,
           5.    ],
        [  7.    ,   0.91  ,   1.0007, ...,   8.9   ,   5.6   ,
          12.1   ]],

       [[  8.    ,   0.9   ,   1.018 , ...,   8.5   ,   5.1   ,
           9.9   ],
        [  6.    ,   0.77  ,   1.0179, ...,   3.1   ,  -0.5   ,
           6.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,   2.7   ,   1.7   ,
           5.3   ],
        ...,
        [  8.    ,   0.93  ,   1.032 , ...,  -9.5   , -10.    ,
          -8.9   ],
        [  5.    ,   0.69  ,   1.0114, ...,   2.4   ,   1.3   ,
           4.1   ],
        [  7.    ,   0.91  ,   1.0096, ...,  10.5   ,   8.1   ,
          12.9   ]],

       ...,

       [[  4.    ,   0.76  ,   1.0227, ...,  16.7   ,  13.1   ,
          22.4   ],
        [  2.    ,   0.68  ,   1.0278, ...,  13.4   ,   8.6   ,
          18.2   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  3.    ,   0.84  ,   1.0263, ...,   3.3   ,   2.1   ,
           4.5   ],
        [  5.    ,   0.85  ,   1.0059, ...,  13.1   ,  12.1   ,
          14.4   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]],

       [[  5.    ,   0.8   ,   1.0212, ...,  15.4   ,  11.6   ,
          21.1   ],
        [  1.    ,   0.68  ,   1.0238, ...,  15.    ,   9.1   ,
          20.9   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  3.    ,   0.84  ,   1.0263, ...,   3.4   ,   2.7   ,
           4.1   ],
        [  5.    ,   0.94  ,   1.016 , ...,   7.5   ,   5.1   ,
          12.4   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]],

       [[  5.    ,   0.84  ,   1.0193, ...,  13.5   ,   9.9   ,
          19.2   ],
        [  4.    ,   0.68  ,   1.0235, ...,  14.4   ,  10.4   ,
          18.4   ],
        [  4.    ,   0.67  ,   1.017 , ...,  11.7   ,   7.9   ,
          16.2   ],
        ...,
        [  4.    ,   0.84  ,   1.0263, ...,   1.7   ,   0.7   ,
           2.7   ],
        [  5.    ,   0.97  ,   1.0164, ...,   9.7   ,   5.    ,
          12.6   ],
        [  5.    ,   0.82  ,   1.0142, ...,  10.7   ,   7.9   ,
          13.5   ]]])

## 3.  Split the data

In [40]:
# Split data into train and test sets

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [42]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(17212, 15, 9) (17212, 15)
(5738, 15, 9) (5738, 15)

## 4.  Keras Model

In [47]:
epochs = 30
batch_size = 16
n_hidden = 64

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(MaxPooling1D())
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='tanh')) # Don't use relu here!

In [49]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 14, 64)         │         1,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 7, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 64)             │        33,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 15)             │           975 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 35,215 (137.56 KB)

 Trainable params: 35,215 (137.56 KB)

 Non-trainable params: 0 (0.00 B)

## 5. Compiling and Running Model

In [52]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [54]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0866 - loss: 25.2647
Epoch 2/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1907 - loss: 24.6085
Epoch 3/30
1076/1076 - 2s - 1ms/step - accuracy: 0.1543 - loss: 24.9159
Epoch 4/30
1076/1076 - 2s - 2ms/step - accuracy: 0.2123 - loss: 24.8038
Epoch 5/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1932 - loss: 24.5199
Epoch 6/30
1076/1076 - 2s - 2ms/step - accuracy: 0.2373 - loss: 24.9833
Epoch 7/30
1076/1076 - 2s - 1ms/step - accuracy: 0.1938 - loss: 24.8887
Epoch 8/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1577 - loss: 24.5110
Epoch 9/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1063 - loss: 24.0851
Epoch 10/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1667 - loss: 24.8757
Epoch 11/30
1076/1076 - 2s - 2ms/step - accuracy: 0.2267 - loss: 24.8200
Epoch 12/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1931 - loss: 24.7648
Epoch 13/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0853 - loss: 24.5965
Epoch 14/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0859 - loss: 24.6746
Epoch 15/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1638 - loss: 24.8987
Epoch 16/30
1076/1076 - 2s - 1ms/step - accuracy: 0.1322 - loss: 24.4474
Epoch 17/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0974 - loss: 24.6236
Epoch 18/30
1076/1076 - 2s - 2ms/step - accuracy: 0.2107 - loss: 24.8791
Epoch 19/30
1076/1076 - 2s - 2ms/step - accuracy: 0.2075 - loss: 24.6161
Epoch 20/30
1076/1076 - 2s - 2ms/step - accuracy: 0.2198 - loss: 24.5026
Epoch 21/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0589 - loss: 24.5047
Epoch 22/30
1076/1076 - 2s - 1ms/step - accuracy: 0.0435 - loss: 24.2501
Epoch 23/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1045 - loss: 24.3699
Epoch 24/30
1076/1076 - 2s - 2ms/step - accuracy: 0.1084 - loss: 24.2773
Epoch 25/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0790 - loss: 24.6361
Epoch 26/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0469 - loss: 24.2582
Epoch 27/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0800 - loss: 24.5896
Epoch 28/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0788 - loss: 24.5523
Epoch 29/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0543 - loss: 24.5272
Epoch 30/30
1076/1076 - 2s - 2ms/step - accuracy: 0.0410 - loss: 24.9091

### 6. Confusion Matrix

In [59]:
# Define list of stations names

stations = {
0: 'BASEL',
1: 'BELGRADE',
2: 'BUDAPEST',
3: 'DEBILT',
4: 'DUSSELDORF',
5: 'HEATHROW',
6: 'KASSEL',
7: 'LJUBLJANA',
8: 'MAASTRICHT',
9: 'MADRID',
10: 'MUNCHENB',
11: 'OSLO',
12: 'SONNBLICK',
13: 'STOCKHOLM',
14: 'VALENTIA'

}

In [61]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [63]:
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step
Pred        DEBILT
True
BASEL         3682
BELGRADE      1092
BUDAPEST       214
DEBILT          82
DUSSELDORF      29
HEATHROW        82
KASSEL          11
LJUBLJANA       61
MAASTRICHT       9
MADRID         458
MUNCHENB         8
OSLO             5
STOCKHOLM        4
VALENTIA         1

### 7. Keras Model Retrials (Until Convergence)

In [65]:
epochs = 30
batch_size = 16
n_hidden = 4

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='softmax')) # Options: sigmoid, tanh, softmax, relu

In [67]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_1 (Conv1D)               │ (None, 14, 4)          │            76 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 14, 16)         │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,851 (7.23 KB)

 Trainable params: 1,851 (7.23 KB)

 Non-trainable params: 0 (0.00 B)

In [69]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [71]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 1s - 727us/step - accuracy: 0.1250 - loss: 557.7563
Epoch 2/30
1076/1076 - 0s - 430us/step - accuracy: 0.1403 - loss: 5722.4106
Epoch 3/30
1076/1076 - 0s - 427us/step - accuracy: 0.1374 - loss: 19827.1348
Epoch 4/30
1076/1076 - 0s - 437us/step - accuracy: 0.1348 - loss: 42401.4336
Epoch 5/30
1076/1076 - 0s - 424us/step - accuracy: 0.1300 - loss: 77156.0234
Epoch 6/30
1076/1076 - 0s - 434us/step - accuracy: 0.1324 - loss: 119901.1641
Epoch 7/30
1076/1076 - 0s - 438us/step - accuracy: 0.1356 - loss: 177225.4688
Epoch 8/30
1076/1076 - 0s - 434us/step - accuracy: 0.1336 - loss: 244201.5000
Epoch 9/30
1076/1076 - 0s - 428us/step - accuracy: 0.1369 - loss: 331277.6875
Epoch 10/30
1076/1076 - 0s - 424us/step - accuracy: 0.1330 - loss: 432608.2500
Epoch 11/30
1076/1076 - 0s - 422us/step - accuracy: 0.1316 - loss: 546798.0000
Epoch 12/30
1076/1076 - 0s - 425us/step - accuracy: 0.1282 - loss: 681154.5625
Epoch 13/30
1076/1076 - 0s - 442us/step - accuracy: 0.1348 - loss: 835671.6875
Epoch 14/30
1076/1076 - 0s - 423us/step - accuracy: 0.1353 - loss: 1008618.2500
Epoch 15/30
1076/1076 - 0s - 420us/step - accuracy: 0.1297 - loss: 1208326.6250
Epoch 16/30
1076/1076 - 0s - 420us/step - accuracy: 0.1296 - loss: 1424933.5000
Epoch 17/30
1076/1076 - 0s - 424us/step - accuracy: 0.1304 - loss: 1665202.2500
Epoch 18/30
1076/1076 - 0s - 432us/step - accuracy: 0.1257 - loss: 1927573.7500
Epoch 19/30
1076/1076 - 0s - 431us/step - accuracy: 0.1305 - loss: 2207755.7500
Epoch 20/30
1076/1076 - 0s - 427us/step - accuracy: 0.1297 - loss: 2519530.0000
Epoch 21/30
1076/1076 - 0s - 441us/step - accuracy: 0.1274 - loss: 2868173.2500
Epoch 22/30
1076/1076 - 0s - 461us/step - accuracy: 0.1261 - loss: 3268160.2500
Epoch 23/30
1076/1076 - 0s - 442us/step - accuracy: 0.1236 - loss: 3669178.0000
Epoch 24/30
1076/1076 - 0s - 424us/step - accuracy: 0.1277 - loss: 4103932.2500
Epoch 25/30
1076/1076 - 0s - 426us/step - accuracy: 0.1268 - loss: 4554260.5000
Epoch 26/30
1076/1076 - 0s - 423us/step - accuracy: 0.1271 - loss: 5075183.5000
Epoch 27/30
1076/1076 - 0s - 422us/step - accuracy: 0.1258 - loss: 5610413.0000
Epoch 28/30
1076/1076 - 0s - 423us/step - accuracy: 0.1282 - loss: 6183999.5000
Epoch 29/30
1076/1076 - 0s - 423us/step - accuracy: 0.1247 - loss: 6803855.0000
Epoch 30/30
1076/1076 - 0s - 420us/step - accuracy: 0.1250 - loss: 7459161.5000

In [73]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [75]:
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 378us/step
Pred        BELGRADE  BUDAPEST  DEBILT  HEATHROW  KASSEL  LJUBLJANA  \
True
BASEL            233       730     100         4      12        242
BELGRADE         149       262      10         0       1         77
BUDAPEST          22        52       2         0       0         14
DEBILT            12         6       1         0       0          2
DUSSELDORF         3         3       0         0       0          0
HEATHROW           3         4       2         0       0          2
KASSEL             3         1       1         0       0          0
LJUBLJANA          2        13       0         0       0          8
MAASTRICHT         0         2       0         0       0          0
MADRID            16        56      10         3       1         23
MUNCHENB           3         2       0         0       0          1
OSLO               1         0       0         0       0          0
STOCKHOLM          1         2       0         0       0          0
VALENTIA           0         0       1         0       0          0

Pred        MAASTRICHT  MADRID  MUNCHENB  OSLO  SONNBLICK  STOCKHOLM  VALENTIA
True
BASEL              543     661       959    99          9         51        39
BELGRADE            68     106       401    15          0          3         0
BUDAPEST            17      32        68     6          0          1         0
DEBILT              15       4        35     5          0          2         0
DUSSELDORF          11       5         7     0          0          0         0
HEATHROW            23      29        15     3          0          1         0
KASSEL               1       1         3     1          0          0         0
LJUBLJANA            5      26         5     2          0          0         0
MAASTRICHT           0       2         5     0          0          0         0
MADRID              87     194        44    17          0          7         0
MUNCHENB             0       0         1     1          0          0         0
OSLO                 0       1         0     3          0          0         0
STOCKHOLM            0       1         0     0          0          0         0
VALENTIA             0       0         0     0          0          0         0

### Softmax is not producing good results, try with tanh, sigmoid, and Relu.

In [78]:
epochs = 30
batch_size = 16
n_hidden = 128

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='tanh')) # Options: sigmoid, tanh, softmax, relu

In [80]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_2 (Conv1D)               │ (None, 14, 128)        │         2,432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 14, 16)         │         2,064 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,191 (24.18 KB)

 Trainable params: 6,191 (24.18 KB)

 Non-trainable params: 0 (0.00 B)

In [82]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [84]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 1s - 883us/step - accuracy: 0.0033 - loss: 25.4100
Epoch 2/30
1076/1076 - 1s - 573us/step - accuracy: 0.0012 - loss: 25.7457
Epoch 3/30
1076/1076 - 1s - 580us/step - accuracy: 9.2958e-04 - loss: 25.7429
Epoch 4/30
1076/1076 - 1s - 585us/step - accuracy: 9.2958e-04 - loss: 25.7429
Epoch 5/30
1076/1076 - 1s - 570us/step - accuracy: 9.8768e-04 - loss: 25.7391
Epoch 6/30
1076/1076 - 1s - 571us/step - accuracy: 9.8768e-04 - loss: 25.7391
Epoch 7/30
1076/1076 - 1s - 652us/step - accuracy: 9.8768e-04 - loss: 25.7372
Epoch 8/30
1076/1076 - 1s - 658us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 9/30
1076/1076 - 1s - 580us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 10/30
1076/1076 - 1s - 584us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 11/30
1076/1076 - 1s - 603us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 12/30
1076/1076 - 1s - 589us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 13/30
1076/1076 - 1s - 610us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 14/30
1076/1076 - 1s - 593us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 15/30
1076/1076 - 1s - 585us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 16/30
1076/1076 - 1s - 605us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 17/30
1076/1076 - 1s - 657us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 18/30
1076/1076 - 1s - 586us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 19/30
1076/1076 - 1s - 578us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 20/30
1076/1076 - 1s - 585us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 21/30
1076/1076 - 1s - 582us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 22/30
1076/1076 - 1s - 592us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 23/30
1076/1076 - 1s - 588us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 24/30
1076/1076 - 1s - 690us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 25/30
1076/1076 - 1s - 596us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 26/30
1076/1076 - 1s - 581us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 27/30
1076/1076 - 1s - 613us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 28/30
1076/1076 - 1s - 644us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 29/30
1076/1076 - 1s - 596us/step - accuracy: 9.8768e-04 - loss: 25.7363
Epoch 30/30
1076/1076 - 1s - 582us/step - accuracy: 9.8768e-04 - loss: 25.7363

In [92]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [94]:
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 476us/step
Pred        BASEL  DEBILT  DUSSELDORF  STOCKHOLM  VALENTIA
True
BASEL           1       1         124       1156      2400
BELGRADE        0       0           0        324       768
BUDAPEST        0       1           0         59       154
DEBILT          0       0           0         37        45
DUSSELDORF      0       0           0          9        20
HEATHROW        0       0           0         18        64
KASSEL          0       0           0          6         5
LJUBLJANA       0       0           0         13        48
MAASTRICHT      0       0           0          0         9
MADRID          0       0           2         83       373
MUNCHENB        0       0           0          1         7
OSLO            0       0           0          3         2
STOCKHOLM       0       0           0          0         4
VALENTIA        0       0           0          1         0

### Model's loss is decreasing (which is good), but we're not seeing that improvement reflected in accuracy. We need to try adjusting layers.

In [97]:
epochs = 30
batch_size = 16
n_hidden = 64

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='tanh')) # Options: sigmoid, tanh, softmax, relu

In [99]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_3 (Conv1D)               │ (None, 14, 64)         │         1,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 14, 16)         │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,951 (15.43 KB)

 Trainable params: 3,951 (15.43 KB)

 Non-trainable params: 0 (0.00 B)

In [101]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [103]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 1s - 868us/step - accuracy: 0.0131 - loss: 25.0090
Epoch 2/30
1076/1076 - 1s - 644us/step - accuracy: 0.0150 - loss: 27.0565
Epoch 3/30
1076/1076 - 1s - 573us/step - accuracy: 0.0198 - loss: 27.3339
Epoch 4/30
1076/1076 - 1s - 570us/step - accuracy: 0.0189 - loss: 27.9987
Epoch 5/30
1076/1076 - 1s - 575us/step - accuracy: 0.0185 - loss: 27.9987
Epoch 6/30
1076/1076 - 1s - 574us/step - accuracy: 0.0185 - loss: 27.9988
Epoch 7/30
1076/1076 - 1s - 569us/step - accuracy: 0.0183 - loss: 27.9988
Epoch 8/30
1076/1076 - 1s - 572us/step - accuracy: 0.0184 - loss: 27.9988
Epoch 9/30
1076/1076 - 1s - 572us/step - accuracy: 0.0184 - loss: 27.9987
Epoch 10/30
1076/1076 - 1s - 577us/step - accuracy: 0.0184 - loss: 27.9988
Epoch 11/30
1076/1076 - 1s - 572us/step - accuracy: 0.0184 - loss: 27.9987
Epoch 12/30
1076/1076 - 1s - 590us/step - accuracy: 0.0184 - loss: 27.9988
Epoch 13/30
1076/1076 - 1s - 574us/step - accuracy: 0.0184 - loss: 27.9988
Epoch 14/30
1076/1076 - 1s - 567us/step - accuracy: 0.0184 - loss: 27.9988
Epoch 15/30
1076/1076 - 1s - 582us/step - accuracy: 0.0184 - loss: 27.9988
Epoch 16/30
1076/1076 - 1s - 654us/step - accuracy: 0.0184 - loss: 27.9988
Epoch 17/30
1076/1076 - 1s - 631us/step - accuracy: 0.0184 - loss: 27.9987
Epoch 18/30
1076/1076 - 1s - 594us/step - accuracy: 0.0184 - loss: 27.9988
Epoch 19/30
1076/1076 - 1s - 583us/step - accuracy: 0.0184 - loss: 27.9987
Epoch 20/30
1076/1076 - 1s - 571us/step - accuracy: 0.0184 - loss: 27.9987
Epoch 21/30
1076/1076 - 1s - 578us/step - accuracy: 0.0184 - loss: 27.9988
Epoch 22/30
1076/1076 - 1s - 579us/step - accuracy: 0.0184 - loss: 27.9987
Epoch 23/30
1076/1076 - 1s - 574us/step - accuracy: 0.0184 - loss: 27.9988
Epoch 24/30
1076/1076 - 1s - 572us/step - accuracy: 0.0184 - loss: 27.9988
Epoch 25/30
1076/1076 - 1s - 569us/step - accuracy: 0.0184 - loss: 27.9987
Epoch 26/30
1076/1076 - 1s - 579us/step - accuracy: 0.0184 - loss: 27.9988
Epoch 27/30
1076/1076 - 1s - 579us/step - accuracy: 0.0184 - loss: 27.9987
Epoch 28/30
1076/1076 - 1s - 592us/step - accuracy: 0.0184 - loss: 27.9988
Epoch 29/30
1076/1076 - 1s - 590us/step - accuracy: 0.0184 - loss: 27.9987
Epoch 30/30
1076/1076 - 1s - 583us/step - accuracy: 0.0184 - loss: 27.9987

In [105]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [107]:
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 460us/step
Pred        DEBILT  DUSSELDORF  HEATHROW  MADRID  MUNCHENB  SONNBLICK  \
True
BASEL         1630          12       416     218      1046         11
BELGRADE       767          15         2      25       127         24
BUDAPEST       177           3         1       4        13          1
DEBILT          70           1         0       1         1          1
DUSSELDORF      23           1         1       0         2          0
HEATHROW        55           1         0       6         5          0
KASSEL           6           1         0       2         0          0
LJUBLJANA       37           0         0       0         9          0
MAASTRICHT       3           0         0       1         2          0
MADRID         300           4         9      50        45          4
MUNCHENB         1           1         0       1         2          0
OSLO             4           0         0       0         0          0
STOCKHOLM        4           0         0       0         0          0
VALENTIA         0           0         0       0         0          0

Pred        STOCKHOLM  VALENTIA
True
BASEL             298        51
BELGRADE          132         0
BUDAPEST           15         0
DEBILT              8         0
DUSSELDORF          2         0
HEATHROW           15         0
KASSEL              2         0
LJUBLJANA          15         0
MAASTRICHT          3         0
MADRID             44         2
MUNCHENB            3         0
OSLO                1         0
STOCKHOLM           0         0
VALENTIA            1         0

### Loss is not is stable but not as low as expected, accuracy is much higher. Try with sigmoid and relu.

In [110]:
epochs = 30
batch_size = 16
n_hidden = 64

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=2, activation='relu', input_shape=(timesteps, input_dim)))
model.add(Dense(16, activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='sigmoid')) # Options: sigmoid, tanh, softmax, relu

In [112]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_4 (Conv1D)               │ (None, 14, 64)         │         1,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 14, 16)         │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_4 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 15)             │         1,695 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,951 (15.43 KB)

 Trainable params: 3,951 (15.43 KB)

 Non-trainable params: 0 (0.00 B)

In [114]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [116]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/30
1076/1076 - 1s - 845us/step - accuracy: 0.6221 - loss: 9617.2656
Epoch 2/30
1076/1076 - 1s - 552us/step - accuracy: 0.6432 - loss: 99427.4766
Epoch 3/30
1076/1076 - 1s - 566us/step - accuracy: 0.6434 - loss: 319140.3438
Epoch 4/30
1076/1076 - 1s - 572us/step - accuracy: 0.6434 - loss: 725537.8750
Epoch 5/30
1076/1076 - 1s - 577us/step - accuracy: 0.6434 - loss: 1304382.8750
Epoch 6/30
1076/1076 - 1s - 560us/step - accuracy: 0.6434 - loss: 2091254.7500
Epoch 7/30
1076/1076 - 1s - 554us/step - accuracy: 0.6435 - loss: 3066805.5000
Epoch 8/30
1076/1076 - 1s - 555us/step - accuracy: 0.6436 - loss: 4196246.5000
Epoch 9/30
1076/1076 - 1s - 595us/step - accuracy: 0.6437 - loss: 5708821.5000
Epoch 10/30
1076/1076 - 1s - 551us/step - accuracy: 0.6437 - loss: 7328497.0000
Epoch 11/30
1076/1076 - 1s - 554us/step - accuracy: 0.6437 - loss: 9340031.0000
Epoch 12/30
1076/1076 - 1s - 554us/step - accuracy: 0.6437 - loss: 11615387.0000
Epoch 13/30
1076/1076 - 1s - 554us/step - accuracy: 0.6437 - loss: 14374781.0000
Epoch 14/30
1076/1076 - 1s - 580us/step - accuracy: 0.6437 - loss: 17320762.0000
Epoch 15/30
1076/1076 - 1s - 567us/step - accuracy: 0.6437 - loss: 20846166.0000
Epoch 16/30
1076/1076 - 1s - 675us/step - accuracy: 0.6437 - loss: 24717202.0000
Epoch 17/30
1076/1076 - 1s - 583us/step - accuracy: 0.6437 - loss: 28892162.0000
Epoch 18/30
1076/1076 - 1s - 558us/step - accuracy: 0.6437 - loss: 33615856.0000
Epoch 19/30
1076/1076 - 1s - 585us/step - accuracy: 0.6437 - loss: 38488988.0000
Epoch 20/30
1076/1076 - 1s - 610us/step - accuracy: 0.6437 - loss: 44432808.0000
Epoch 21/30
1076/1076 - 1s - 560us/step - accuracy: 0.6437 - loss: 50142788.0000
Epoch 22/30
1076/1076 - 1s - 552us/step - accuracy: 0.6437 - loss: 56840280.0000
Epoch 23/30
1076/1076 - 1s - 609us/step - accuracy: 0.6437 - loss: 64049112.0000
Epoch 24/30
1076/1076 - 1s - 596us/step - accuracy: 0.6437 - loss: 71829424.0000
Epoch 25/30
1076/1076 - 1s - 628us/step - accuracy: 0.6438 - loss: 80094520.0000
Epoch 26/30
1076/1076 - 1s - 577us/step - accuracy: 0.6438 - loss: 88352840.0000
Epoch 27/30
1076/1076 - 1s - 561us/step - accuracy: 0.6438 - loss: 97845552.0000
Epoch 28/30
1076/1076 - 1s - 562us/step - accuracy: 0.6438 - loss: 108565176.0000
Epoch 29/30
1076/1076 - 1s - 560us/step - accuracy: 0.6438 - loss: 119060784.0000
Epoch 30/30
1076/1076 - 1s - 623us/step - accuracy: 0.6438 - loss: 130606680.0000

In [118]:
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [120]:
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 472us/step
Pred        BASEL
True
BASEL        3682
BELGRADE     1092
BUDAPEST      214
DEBILT         82
DUSSELDORF     29
HEATHROW       82
KASSEL         11
LJUBLJANA      61
MAASTRICHT      9
MADRID        458
MUNCHENB        8
OSLO            5
STOCKHOLM       4
VALENTIA        1